module.exports = {
    token: 'lmasm_wechat',
    appId: 'wx974a72c6b6b557e0',
    appsecret: '8937aaf3ebfb46dc8694bfe2fc656fb3',
    // templateId: 'sXhyW5ykd_CPnglc7kHxH_yDvyTe-flIc26j7PRlF7k',
    templateId: 'WihXoPTYmGm301jEjfcY-22JVEcxHtaj1i5cCTifCmw',
    mineOpenId: 'ouOxQ51Sub6AEVxAyDfwolzegy2w',
    myBirthday: '07-24',
    laichenOpenId: 'ouOxQ57UJlCh27Z7szltCXayPmjQ',
    laichenBirthday: '10-24',
    gaodeKey: '83ac465d391648e8bb819de9e484a243',
    xiAnCityCode: '610100',
    beijingCityCode: '110000',
    zhengzhouCityCoe: '410102',
    dongdongBirthday: '12-02',
    dongdongOpenId: 'ouOxQ55zwKCq9DlG90u4NBqg5M18',
    list: [
        '玫瑰到了花期，我很想你。',
        '凌晨四点半，海棠花未眠。总觉得这时候，你应该在我身边。',
        '龙应该藏在云里，你应该藏在心里。',
        '突然很喜欢惊鸿一瞥这个词，一见钟情太肤浅，日久生情太苍白，别人眉来眼去，我呀，只偷看你一眼。',
        '晓看天色暮看云，行也思君，坐也思君。',
        '我不看月亮，也不说想你，这样月亮和你都蒙在鼓里',
        '大家都说我性子很慢，其实我可以很快，比如，后面有狗在追我，或者，你在前面等我。',
        '人间烟火，山河远阔，无一是你，无一不是你。',
        '我们就住在这里把，胭脂用尽时，桃花就开了。',
        '傍晚的月亮照着花开的田野。',
        '潮水撞击河岸，玉林窃窃私语。此时风动，也是心动。',
        '花盛开就是一句，夜漫过就是一篇，黄昏开始书写，黎明是无数的扉页。',
        '你知道为什么月亮两头尖尖，中间弧形吗？锋芒对外，温柔对你。',
        '在这陌生城市的一日光景，哪里有心思看风景，除了你都是背景。',
        '我喜欢三月的风，六月的雨，不落的太阳，和最好的你。',
        '清醒知趣，保持自信，一切尽意，百事从欢。',
        '今天的你也辛苦啦',
        '天上只有一个月亮，世上也只有一个你呀。',
        '温柔是宝藏，你也是。',
        '愿日子滚烫，快乐又明亮。',
        '慢品人间烟火色，闲观万事岁月长。',
        '任何浪漫源于爱自己。',
        '目光所及之处，皆是我此生向往。',
        '跟你在一起的时光都很耀眼，因为天气好，因为天气不好，因为天气刚刚好。',
        '你没空的时候我就自己玩，你有空了记得找我玩。',
    ]
}